package io.nyxbit.phinma

import android.graphics.Color
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.lifecycle.ViewModelProvider
import io.nyxbit.phinma.databinding.FragmentCourseOfferingBinding


class CourseOffering : Fragment() {


    private lateinit var binding : FragmentCourseOfferingBinding
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        binding = FragmentCourseOfferingBinding.inflate(inflater,container,false)
        val viewModel = ViewModelProvider(requireActivity())[ViewModel::class.java]
        binding.header.header.setBackgroundColor(Color.parseColor(viewModel.school.primaryColor))
        val dataset = mutableListOf(
            Data("PHINMA UPang Basic Education Unit", "Offers the youth relevant basic skills and knowledge to prepare them for higher learning in tertiary education. The University’s Basic Ed curriculum follows the K to 12 basic education program, including the following Senior High School strands student could choose from: Accountancy and Business Management (ABM), Humanities and Social Sciences (HUMSS), Science, Technology, Engineering and Math (STEM), General Academics (GAS) and Technical-Vocational-Livelihood Track (TVL)."),
            Data("Bachelor of Science in Accountancy", "The Bachelor of Science in Accountancy program is a four-year course that prepares students for a professional career in Accountancy, particularly in Public Accounting. The program aims to guide students by providing them technical knowledge, skills and abilities required in the accountancy profession. We also help them develop the values of integrity, independence and skepticism necessary for making professional judgments. Our program uses a competency framework for professional accountants from the International Federation of Accountants, so that graduates may take certifications in Accountancy by the Philippine Professional Regulatory Commission and other international certifying bodies."),
            Data("Bachelor of Science in Management Accounting", "The Bachelor of Science in Management Accounting program emphasizes the development of technical knowledge, skills, and values necessary for a successful career in management accounting. Our curriculum is designed to provide students with a strong foundation in accounting principles, financial analysis, cost management, and strategic decision-making. Graduates of our program are well-prepared to pursue professional certifications in management accounting, enabling them to demonstrate their expertise and enhance their career prospects."),
            Data("Bachelor of Science in Accountancy Technology", "The Bachelor of Science in Accounting Technology program focuses on cultivating the technical expertise, skills, and values essential for a thriving career in accounting management. Our curriculum is meticulously crafted to furnish students with a robust grounding in accounting principles, financial analysis, cost management, and strategic decision-making. Upon completion, our graduates are adeptly equipped to pursue professional certifications in accounting management, showcasing their proficiency and elevating their career opportunities."),
            Data("Bachelor of Science in Hospitality Management", "The Bachelor of Science in Hospitality Management is a program which trains students in a diverse set of skills necessary to Hospitality professionals. Using experiential teaching methods, we hone their skills in Housekeeping, Front Office, Food and Beverage Services, Culinary, Events Planning and Cruise Line Operations. We develop their communication skills so they can properly address the needs and preferences of guests as professionals. We also teach our students the values of cultural diversity, sensitivity and versatility needed in working with and serving guests from different cultures. Most importantly, the program provides students the opportunity to earn local and international certifications and diplomas (TESDA, American Hospitality and Lodging Education Institute, School D’ Hospitality of Singapore) to make them globally-competitive."),
            Data("Bachelor of Science in Tourism Management", "The Bachelor of Science in Tourism Management trains students in a diverse set of skills necessary for their future careers. We use the active learning methodology in honing students’ skills in functional areas like Front Office, Events Planning, Cruise Line Operations, and Travel and Tours. We develop their communication skills so they can properly guide guests through destinations and address their needs and concerns. We also teach our students the values of cultural diversity, sensitivity and versatility needed in touring guests from different cultures. Most importantly, we instill within them the value of our heritage and culture, so that they may best represent the country as our ambassadors.  Our program provides students the chance to earn local and international certifications and diplomas (TESDA, American Hospitality and Lodging Education Institute, School D’ Hospitality of Singapore) for prestigious local and global employment opportunities."),
            Data("Bachelor of Science in Business Administration", "The Bachelor of Science in Business Administration (BSBA) program through its various fields of specializations guides students to become competent finance, marketing, and human resource professionals. Graduates are also prepared to become successful entrepreneurs and business leaders. Through a competency-based curriculum, students are able to hone basic business skills such as financial analysis, business administration, project management, and product presentation through research and feasibility studies. We help them identify trends and developments in various business industries to prepare them ahead of the real world. We engage in partnerships with industry leaders so they can learn how to work in an actual office setting. We also develop their communication, critical thinking, and problem solving skills. Lastly, but not the least, we teach them the values of resourcefulness, creativity, discipline and teamwork."),
            Data("Bachelor of Arts in Communication", "The Bachelor of Arts in Communication (AB Communication) is a comprehensive degree program designed to prepare students for dynamic roles in the field of communication. Through a blend of theoretical foundations and hands-on practical experience, this program equips students with the essential knowledge and skills required for effective communication across various mediums. From journalism and public relations to digital media and interpersonal communication, our curriculum covers a wide spectrum, empowering graduates to navigate and excel in the diverse and ever-evolving communication landscape. Upon completion, our students are poised to contribute meaningfully to the field, whether in media, corporate communication, or other communication-related professions."),
            Data("Bachelor of Arts in Political Science", "The Bachelor of Arts in Political Science (AB Political Science) is a comprehensive academic program tailored to prepare students for roles in the dynamic field of political science. This program combines theoretical insights with practical applications to impart the necessary knowledge and skills for understanding political systems, policy analysis, and global affairs. With a focus on critical thinking, research, and effective communication, our curriculum equips students to analyze political structures, engage in informed discourse, and contribute meaningfully to the democratic process. Graduates of our program are well-positioned for a range of careers in government, international relations, law, advocacy, and public service."),
            Data("Bachelor of Science in Elementary Education", "The Bachelor of Science in Elementary Education (BSEE) is a four-year degree program meticulously crafted to equip students for a career as elementary school educators. This program seamlessly integrates theory and practical training, ensuring that students acquire the essential knowledge and skills required for effective teaching in elementary schools. Our overarching goal is to cultivate competent educators who foster a conducive learning environment for their students."),
            Data("Bachelor of Secondary Education", "Bachelor of Secondary Education (BSED) is a four year degree program designed to prepare students for becoming high school teachers. The program combines both theory and practice in order to teach students the necessary knowledge and skills a high school teacher needs. The program aims to produce competent teachers who provide a conducive learning experience to their students."),
            Data("Bachelor of Science in Criminology", "The Bachelor of Science in Criminology program is a four-year course that provides students with knowledge and skills in forensic science, criminal jurisprudence, law enforcement, criminal investigation, and correctional administration. We train our students to be efficient and effective public safety and security while maintaining human rights. We also teach them the importance of nationalism and nation-building through protection."),
            Data("Bachelor of Science in Architecture", "The Bachelor of Architecture program is a comprehensive and innovative course designed to cultivate the skills, knowledge, and creative vision necessary for a successful career in architecture. Our curriculum seamlessly integrates theoretical principles with hands-on design projects, providing students with a solid foundation in architectural theory, history, and technical expertise. Through studio-based learning and real-world applications, students develop the ability to conceptualize and bring to life architectural designs that are both aesthetically compelling and functionally sound. Graduates of our program are well-prepared to embark on diverse career paths in architecture, urban planning, sustainable design, and other related fields, contributing to the built environment with ingenuity and expertise."),
            Data("Bachelor of Science in  Computer Engineering", "The Bachelor of Science in Computer Engineering (BS Computer Engineering) program is a dynamic and rigorous course designed to prepare students for the ever-evolving field of computer engineering. Our curriculum combines theoretical foundations with hands-on practical experience, ensuring students acquire a strong understanding of both hardware and software aspects of computing systems. Through courses in digital systems, computer architecture, programming, and electronics, students develop the skills necessary for designing and implementing innovative solutions. The program emphasizes problem-solving, critical thinking, and teamwork, essential for addressing the challenges of the digital age. Graduates are well-equipped for careers in areas such as embedded systems, networking, software development, and hardware design, contributing to advancements in technology and computing."),
            Data("Bachelor of Science in Civil Engineering", "The Bachelor of Science in Civil Engineering program is a four-year course that teaches students the knowledge, skills, and training necessary for designing, constructing and maintaining buildings, and public infrastructure and facilities. We also develop their zest for excellence and lifelong training necessary for adapting to civil engineering trends. Graduates of the BS Civil Engineering program must take the board exams conducted by the Professional Regulation Commission to become professionals."),
            Data("Bachelor of Science in Electrical Engineering", "The Bachelor of Science in Electrical Engineering is a five-year degree program that focuses on conceptualizing, developing, and designing a safe, economical, and ethical utilization of electrical energy. The program also trains students to effectively develop and test real-life applications of electrical circuitry, digital systems, electrical equipment, and machinery control."),
            Data("Bachelor of Science in Mechanical Engineering", "The Bachelor of Science in Mechanical Engineering is a comprehensive and dynamic degree program dedicated to equipping students with the knowledge and skills essential for conceptualizing, designing, and optimizing mechanical systems. Our curriculum emphasizes the safe, cost-effective, and ethical utilization of energy in mechanical processes. Students are trained to proficiently develop and test real-world applications of mechanical principles, including machinery design, thermodynamics, fluid mechanics, and materials science. Through a blend of theoretical knowledge and practical experience, graduates of our program are well-prepared to contribute to industries such as manufacturing, automotive, aerospace, and energy, where they play a crucial role in innovation, problem-solving, and the advancement of mechanical technology."),
            Data("Bachelor of Science in Electrical Engineering", "The Bachelor of Science in Electrical Engineering is a dynamic and comprehensive degree program focused on preparing students for the intricacies of electrical systems. Emphasizing the safe, efficient, and ethical utilization of electrical energy, our curriculum covers critical areas such as electrical circuitry, digital systems, and the effective application of electrical equipment. Through hands-on experiences and theoretical knowledge, students learn to design and test real-life applications, ensuring they are well-equipped for careers in diverse fields such as power systems, electronics, telecommunications, and automation. Our program not only emphasizes technical expertise but also instills a commitment to ethical practices and innovation in the ever-evolving field of electrical engineering."),
            Data("Bachelor of Science in Nursing", "The Bachelor of Science Nursing program is a four-year course where we teach students nursing concepts alongside Related Learning Experiences (RLE). Through our outcome-based curriculum, we train students to become competent through simulated clinical and active learning activities. Our program also provides an intensive nursing practicum that will make our students skilled, refined, and worthy of entering the nursing profession."),
            Data("Bachelor of Science in Pharmacy", "The Bachelor of Science in Pharmacy program is a four-year course which focuses on teaching necessary foundational knowledge for pharmaceutical product development. Through our program, we teach students on the essentials of pharmaceutical chemistry, pharmaceutics, and the life sciences.  During their fourth year, we will assign students to intern in various CHED-accredited affiliated establishments to learn about the rigors of pharmacy practice. Their internship will expose them to various practice areas and prepare them for the roles they may take on after graduation. Graduates of the BS Pharmacy program must take the board exams conducted by the Professional Regulation Commission to qualify as registered pharmacists."),
            Data("Bachelor in Medical Laboratory Science", "The Bachelor of Science in Medical Laboratory Science is a four-year program that provides knowledge in the fields of Clinical Chemistry, Hematology, Microbiology, Immunohematology, Immunology and Serology, Urinalysis, Clinical Microscopy, Parasitology, Cytology, and Histopathology. During their fourth year, students undergo an internship program in a CHED-accredited training laboratory where they rotate between sections. Graduates of the program must take the board exams conducted by the Professional Regulation Commission to qualify as registered medical technologists."),
            Data("Bachelor of Science in Psychology", "The Bachelor of Science in Psychology program focuses on the comprehensive understanding of human behavior and mental processes. Our curriculum is designed to provide students with a strong foundation in psychological theories, research methods, and practical skills. We emphasize the development of critical thinking, ethical reasoning, and effective communication skills to prepare graduates for a successful career in the field of psychology.  Future Career  Graduates of our Bachelor of Science in Psychology program have diverse career opportunities in various industries. They can pursue careers as psychologists, counselors, human resource professionals, research analysts, or social service providers in settings such as hospitals, clinics, educational institutions, government agencies, or nonprofit organizations.  With their strong foundation in psychology, graduates can excel in roles such as clinical psychologists, counseling psychologists, industrial-organizational psychologists, or educational psychologists, contributing to mental well-being, performance improvement, and community development. They may also specialize in areas such as child psychology, forensic psychology, sports psychology, or health psychology, and have the option to pursue advanced degrees to enhance their knowledge and career prospects."),
            Data("Bachelor of Science in Information Technology", "The Bachelor of Science in Information Technology program provides students with skills and knowledge needed in relevant emerging high-growth areas in the industry. Through our program, we train students with the development and management of contemporary areas such as cloud computing and applications, analytics and data science, artificial intelligence, and the Internet of Things. We use a curriculum based on inputs and guidance from practicing industry experts."),
            Data("Bachelor of Science in Computer Science", "The Bachelor of Science in Computer Science (BSCS) program is designed to provide students with a strong foundation in computing concepts, algorithms, and programming. It emphasizes the development of software applications and the understanding of hardware-software interactions. Students are equipped with the skills necessary for careers in software development, systems analysis, and IT management. The curriculum includes hands-on experience in programming languages, data structures, algorithms, and system design, preparing graduates for a rapidly evolving technology landscape."),
            Data("Bachelor of Science in Information Systems", "The Bachelor of Science in Information Systems (BSIS) program focuses on the study of information management and technology in business environments. The curriculum covers areas such as systems analysis and design, database management, and IT project management. Students are trained to develop and manage information systems that support business processes, decision-making, and organizational performance. Graduates are prepared for careers in IT management, systems development, and information strategy in various industries."),
            Data("Bachelor of Science in Electronics Engineering", "The Bachelor of Science in Electronics Engineering (BSECE) program provides students with a comprehensive education in electronics, telecommunications, and embedded systems. The program emphasizes the design, development, and implementation of electronic circuits, devices, and communication systems. Students gain practical experience in digital and analog electronics, signal processing, and telecommunications, preparing them for careers in industries such as telecommunications, consumer electronics, and aerospace.")
        )
        val adapter = CourseRecyclerAdapter(dataset, viewModel)
        binding.recyclerCourse.adapter = adapter
        return binding.root
    }


}